### PR TITLE
Support for smalldatetime column type

### PR DESCRIPTION
**Pull request by pauliusg**

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @pauliusg ,

Thank you for the pull, we will try to merge it during the weekend.

Best Regards,

Jonathan

**Comment by pauliusg** [comment]
@JonathanMagnan, any news on this?

**Comment by JonathanMagnan** [comment]
Hello @pauliusg ,

I'm not sure exactly when this request has been made but it's already part of the latest released.

You can see it here: https://github.com/zzzprojects/EntityFramework-Effort/blob/master/Main/Source/Effort.Shared/EffortProviderManifest.xml#L164

I asked my developer to test the latest version and he told me everything worked fine.

Could you try it on your side?

Best Regards,

Jonathan

**Comment by pauliusg** [comment]
Tested, code is in 1.3.5 release and is working. You can close this PR.

**Pull request closed without merging**
